services:
  frontend:
    env_file: "./.env.prod"
    image: ghcr.io/dtx-dota/website/frontend:latest
    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    restart: always

  backend:
    env_file: "./.env.prod"
    image: ghcr.io/dtx-dota/website/backend:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
