services:
  frontend:
    env_file: "./.env.prod"
    image: ghcr.io/dtx-dota/website/frontend:latest
    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    restart: always

  backend:
    env_file: "./.env.prod"
    image: ghcr.io/dtx-dota/website/backend:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  nginx:
    image: ghcr.io/dtx-dota/website/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./.env.prod"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dtxdota.com/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dtxdota.com/privkey.pem
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d

    depends_on:
      - frontend
      - backend
