services:
  frontend:
    container_name: frontend
    image: ghcr.io/dtx-dota/website/frontend:latest
    env_file: "./.env.dev"

    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    volumes:
      - ./frontend:/app
    restart: always
    command: ["npx", "react-router", "dev" , "--port", "3000", "--host", "0.0.0.0"]

  backend:
    container_name: backend

    env_file: "./.env.dev"
    image: ghcr.io/dtx-dota/website/backend:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
  nginx:
    image: ghcr.io/dtx-dota/website/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./.env.dev"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dtxdota.com/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dtxdota.com/privkey.pem
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d


    depends_on:
      - frontend
      - backend
  certbot:
    image: certbot/certbot
