services:
  frontend:
    env_file: "./docker/.env.prod"
    image: ghcr.io/kettleofketchup/dtx_website/frontend:latest
    restart: always

  backend:
    env_file: "./docker/.env.prod"
    image: ghcr.io/kettleofketchup/dtx_website/backend:latest
    restart: always
    volumes:
      - ./backend/db.sqlite3:/app/backend/prod.db.sqlite3
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always
  nginx:
    image: ghcr.io/kettleofketchup/dtx_website/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./docker/.env.prod"
    ports:
      - "80:80"
      - "443:443"
    volumes:

      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
    depends_on:
      - frontend
      - backend
