services:
  frontend:
    container_name: frontend
    image: ghcr.io/kettleofketchup/draftforge/frontend-dev:latest
    user: "1000:1000"
    env_file: "./docker/.env.dev"
    volumes:
      - ./frontend:/app
    restart: always

  backend:
    container_name: backend
    env_file: "./docker/.env.dev"
    image: ghcr.io/kettleofketchup/draftforge/backend-dev:latest
    restart: always
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always
  nginx:
    image: ghcr.io/kettleofketchup/draftforge/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./docker/.env.dev"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/


    depends_on:
      - frontend
      - backend

  celery-worker:
    image: ghcr.io/kettleofketchup/draftforge/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "worker", "-l", "info"]
    volumes:
      - ./backend:/app/backend
    env_file: "./docker/.env.dev"
    depends_on:
      - redis
      - backend
    restart: always

  celery-beat:
    image: ghcr.io/kettleofketchup/draftforge/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "beat", "-l", "info"]
    volumes:
      - ./backend:/app/backend
    env_file: "./docker/.env.dev"
    depends_on:
      - redis
      - celery-worker
    restart: always

  discord-bot:
    image: ghcr.io/kettleofketchup/draftforge/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["python", "manage.py", "run_discord_bot"]
    volumes:
      - ./backend:/app/backend
    env_file: "./docker/.env.dev"
    depends_on:
      - redis
      - backend
    restart: always
