services:

  frontend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/dtx_website/frontend:${VERSION}
    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    restart: always

  backend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/dtx_website/backend:${VERSION}
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/prod.db.sqlite3:/app/backend/prod.db.sqlite3
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/.redis_data:/data
    restart: always
  nginx:
    image: ghcr.io/kettleofketchup/dtx_website/nginx:${VERSION}
    env_file: "./docker/.env.release"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/configs/live/dota.kettle.sh/fullchain.pem:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/certbot/configs/live/dota.kettle.sh/privkey.pem:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend
