services:
  frontend:
    container_name: frontend
    image: ghcr.io/kettleofketchup/dtx_website/frontend-dev:latest
    env_file: "./docker/.env.test"
    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    volumes:
      - ./frontend:/app
      - /app/node_modules/.vite/
      - /app/.react-router/
    restart: always
    command: ["npx", "react-router", "dev" , "--port", "3000", "--host", "0.0.0.0"]
    networks:
      - test-network

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/.redis_data:/data
    restart: always
    networks:
      - test-network

  backend:
    container_name: backend
    env_file: "./docker/.env.test"
    image: ghcr.io/kettleofketchup/dtx_website/backend-dev:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    depends_on:
      - redis
    networks:
      - test-network

  # cypress:
  #   container_name: cypress
  #   image:  ghcr.io/kettleofketchup/dtx_website/cypress:latest
  #   working_dir: /app
  #   network_mode: "host"

  #   volumes:
  #     - ./frontend:/app
  #     - ./frontend/cypress/videos:/app/cypress/videos
  #     - ./frontend/cypress/screenshots:/app/cypress/screenshots
  #   environment:
  #     - CI=true
  #     - CYPRESS_baseUrl=https://localhost
  #     - ELECTRON_ENABLE_LOGGING=false
  #     - CYPRESS_VIDEO=true
  #     - CYPRESS_SCREENSHOTS_FOLDER=/app/cypress/screenshots
  #     - CYPRESS_VIDEOS_FOLDER=/app/cypress/videos
  #     - NODE_TLS_REJECT_UNAUTHORIZED=0
  #     - CYPRESS_VERIFY_SSL=false
  #   command: ["cypress", "run", "--headless", "--browser", "chrome"]
  #   depends_on:
  #     - nginx
  #     - frontend
  #     - backend
  #   profiles:
  #     - testing
  nginx:
    image: ghcr.io/kettleofketchup/dtx_website/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./docker/.env.test"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend
    networks:
      test-network:
        aliases:
          - localhost

networks:
  test-network:
    driver: bridge
