services:
  frontend:
    container_name: frontend
    image: ghcr.io/kettleofketchup/dota_tournament/frontend-dev:latest
    env_file: "./docker/.env.test"
    volumes:
      - ./frontend:/app
      - /app/node_modules/.vite/
      - /app/.react-router/
    restart: always
    command: ["npx", "react-router", "dev" , "--port", "3000", "--host", "0.0.0.0"]
    networks:
      - test-network

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always
    networks:
      - test-network

  backend:
    container_name: backend
    env_file: "./docker/.env.test"
    image: ghcr.io/kettleofketchup/dota_tournament/backend-dev:latest
    restart: always
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    depends_on:
      - redis
    networks:
      - test-network
  nginx:
    image: ghcr.io/kettleofketchup/dota_tournament/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./docker/.env.test"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend
    networks:
      test-network:
        aliases:
          - localhost

  celery-worker:
    image: ghcr.io/kettleofketchup/dota_tournament/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "worker", "-l", "info"]
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    env_file: "./docker/.env.test"
    depends_on:
      - redis
      - backend
    restart: always
    networks:
      - test-network

  celery-beat:
    image: ghcr.io/kettleofketchup/dota_tournament/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "beat", "-l", "info"]
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    env_file: "./docker/.env.test"
    depends_on:
      - redis
      - celery-worker
    restart: always
    networks:
      - test-network

  discord-bot:
    image: ghcr.io/kettleofketchup/dota_tournament/backend-dev:latest
    user: "1000:1000"
    entrypoint: ["python", "manage.py", "run_discord_bot"]
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    env_file: "./docker/.env.test"
    depends_on:
      - redis
      - backend
    restart: always
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
