services:

  frontend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/draftforge/frontend:${VERSION}
    user: "1000:1000"
    restart: always

  backend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/draftforge/backend:${VERSION}
    # No ports exposed - accessed only through nginx reverse proxy
    restart: always
    volumes:
      - ./backend/prod.db.sqlite3:/app/backend/prod.db.sqlite3
      - ./backend/.env:/app/backend/.env
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always
  nginx:
    image: ghcr.io/kettleofketchup/draftforge/nginx:${VERSION}
    env_file: "./docker/.env.release"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/configs/live:/etc/letsencrypt/live
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend

  celery-worker:
    image: ghcr.io/kettleofketchup/draftforge/backend:${VERSION}
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "worker", "-l", "info"]
    env_file: "./docker/.env.release"
    volumes:
      - ./backend/.env:/app/backend/.env
    depends_on:
      - redis
      - backend
    restart: always

  celery-beat:
    image: ghcr.io/kettleofketchup/draftforge/backend:${VERSION}
    user: "1000:1000"
    entrypoint: ["celery"]
    command: ["-A", "config", "beat", "-l", "info"]
    env_file: "./docker/.env.release"
    volumes:
      - ./backend/.env:/app/backend/.env
    depends_on:
      - redis
      - celery-worker
    restart: always

  discord-bot:
    image: ghcr.io/kettleofketchup/draftforge/backend:${VERSION}
    user: "1000:1000"
    entrypoint: ["python", "manage.py", "run_discord_bot"]
    env_file: "./docker/.env.release"
    volumes:
      - ./backend/.env:/app/backend/.env
    depends_on:
      - redis
      - backend
    restart: always
