services:

  frontend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/dota_tournament/frontend:${VERSION}
    restart: always

  backend:
    env_file: "./docker/.env.release"
    image: ghcr.io/kettleofketchup/dota_tournament/backend:${VERSION}
    # No ports exposed - accessed only through nginx reverse proxy
    restart: always
    volumes:
      - ./backend/prod.db.sqlite3:/app/backend/prod.db.sqlite3
      - ./backend/.env:/app/backend/.env
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always
  nginx:
    image: ghcr.io/kettleofketchup/dota_tournament/nginx:${VERSION}
    env_file: "./docker/.env.release"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/configs/live/dota.kettle.sh/fullchain.pem:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/certbot/configs/live:/etc/letsencrypt/live
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend
