services:
  frontend:
    container_name: frontend
    image: ghcr.io/kettleofketchup/dtx_website/frontend-dev:latest
    env_file: "./docker/.env.dev"
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
      target: runtime-dev   # ðŸ‘ˆ choose your stage:
    volumes:
      - ./frontend:/app
      - /app/node_modules/
  backend:
    container_name: backend
    env_file: "./docker/.env.dev"
    image: ghcr.io/kettleofketchup/dtx_website/backend-dev:latest
    restart: always
    volumes:
      - ./backend/:/app/backend
      - ./poetry.lock/:/app/poetry.lock
      - ./pyproject.toml/:/app/pyproject.toml
    depends_on:
      - redis
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    volumes:
      - ./backend/.redis_data:/data
    restart: always

  nginx:
    image: ghcr.io/kettleofketchup/dtx_website/nginx:latest
    container_name: nginx
    restart: always
    env_file: "./docker/.env.dev"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template.conf:/etc/nginx/templates/default.template.conf
      - ./nginx/data/ssl/cert.crt:/etc/letsencrypt/live/dota.kettle.sh/fullchain.pem
      - ./nginx/data/ssl/cert.key:/etc/letsencrypt/live/dota.kettle.sh/privkey.pem
      - ./nginx/data/user_conf.d:/etc/nginx/user_conf.d
      - ./nginx/data/certbot/webroot/:/var/www/certbot/
      - ./nginx/data/certbot/work/:/lib/letsencrypt/
      - ./nginx/data/certbot/configs/:/etc/letsencrypt/
      - ./nginx/data/certbot/logs/:/var/log/letsencrypt/
    depends_on:
      - frontend
      - backend
